<template>
  <div class="parent-letter">
    <div class="parent-letter-title">
      <img class="parent-letter-box-left" src="@/asset/images/box2.png" alt="">
      To Parents
      <img class="parent-letter-box-right" src="@/asset/images/box2.png" alt=""></div>
    <div class="parent-letter-content">
      <p>First we wish you have read Scratch founder Mitchel Resnick’s wonderful essays on programming and learning. Particularly, we recommend you read <a href="https://llk.media.mit.edu/scratch/Learning-with-Scratch.pdf" target="_blank">this</a> and <a href="https://www.edutopia.org/kindergarten-creativity-collaboration-lifelong-learning" target="_blank">this</a>.</p>
      <p>Here at Paracraft, we agree 100% with the ideas and believes outlined in the above two essays. Actually Paracraft itself is a strong testimony to those ideas and believes.</p>
      <p>We observe over and over again that when kids first see paracraft, how they get drawn immediately to it and start playing right away. In a school where students just started to know paracraft by watching a 26 mins introductory tutorial video, which only teaches of installation and some basic operations of the software, they started exploring the software immediately and were able to create amazing animations and games. The story of paracraft says strongly that learning is driven by interest. When you see children play and learn paracraft, it is so obvious that learning without interest is not learning at all.</p>
      <p>For people just starting to learn coding, it can be a pain in the neck to type those lines of code out and correcting all the mistakes in order to get the code run correctly. If you have ever learned of programming, you know that. However, we see all the kids diligently typing in the lines of code, correcting them over and over again to get their little programs running. Paracraft is a powerful tool to create 3D scenes and animation movies. If you see our recommended works, you know what complex works can be created using paracraft. There are many shortcuts for building 3D scenes involving keyboard and mouse. The movie editor is also industrial level. However, we witnessed kids grasping all these skills quickly by playing with it and by talking with each other and sharing tips together, like what material block is suited for building what, how to search and find a block you want, how to hide certain things nicely, etc. Many of the things they are sharing with each other are not taught by our instructor. The children just pick them up from their playing with paracraft.</p>
      <p>Let me share another story here. There was a period of time we encouraged parents to learn paracraft together with their children during out workshop sessions. Our intention is to let paracraft be a bridge that connects parents and their children again. Parents welcomed the idea and sat side by side with their kids, and learn together. However, we noticed a clear difference in the way adults learn and the way kids learn. We observe that parents followed the instructor closely and only did what the instructor asked them to do, while the kids were all clicking around, checking out menus and so on in addition to following the instructor (or not). The older the kids we observe, the less we see such kind of behaviors. We also see children often “experiment” with paracraft that we rarely see parents do. For example, in paracraft, you can build blocks, but you can also destroy blocks. Probably with every kid, I saw them keep destroying the blocks of the ground to see what will happen. Finally they would make a big hole, and the main character would fall through it, but wouldn’t keep falling, s/he just float in the air. When you program with paracraft, you can adjust the speed of moving, for example. Normally giving a number 2 to 10 is the normal range. But kids like to change it to 100, 1000 or even bigger, or 0.1, 0.01 or smaller, to just see what will happen. So these are the characteristics of the physical model of the paracraft 3D world. And the kids discovered it by their seemly silly actions. Parents often tried to stop children when they were doing such things. Parents often regard these as just kids’ silly actions. I am a strong advocate for Self-Directed Learning, which means I am generally very supportive of kids exploring things by themselves. But when seeing kids doing things like this, sometimes I couldn’t help thinking whether they were just being silly, until one day I tried the same thing myself. During my learning of paracraft. I intentionally tried to imitate the kids’ doing. As I was trying such “silly” things, I gradually “get” it. It did help me gain a deeper understanding of paracraft. The key is to follow curiosity or interest. There is something intrinsic about the word “curiosity” or “interest”. It means you start to know something, but there is still a great void of knowledge you need to fill in. It means that you like what you see so far, but you are still uncertain of many things. You want to explore, you want to reduce that uncertainty, you want to comprehend it, grasp it and finally be able to apply it. Follow your interests! It leads naturally to learning. And these kinds of things can hardly be planned by the instructor, but the kids will surely cover it by just playing and trying.</p>
      <p>When seeing how adults and kids learn differently during our workshops, I feel I am seeing what life is like originally and how life learns naturally. I looked at those children, and I told myself: this is what life is like at the very beginning. This is how life learns. The more you stayed at school, the more this was taken out of you.
      </p>
      <p>I have been far from that age now. But seeing them helps me connect to my memory at that age again. In my work on education, this happened to me again and again, reminding me how fortunate I am working on education.</p>
      <p>From the story above, I hope you can also come to this realization that learning is only secondary, play is primary. It is not just that you learn best within a context, learning shouldn’t be separated from playing in the first place, if we truly understand what learning is. Too many educators always put learning in the first place, like everything else is just to serve learning. On the contrary, we think play is the primary activity and learning is only the secondary. People should learn and grow continuously and organically. When children were kept inside a school, isolated from playing, from real life and from communities for the purpose of learning, children are not growing up continuously like they used to.</p>
      <p>Schools should be more like kindergartens, not the other way around. I hope more people can see that.</p>
      <p>Paracraft’s mission is to create a parallel world, for which we coined the word “ParaWorld”, where everyone can create their own games or creative 3D works, where people can keep themselves busy, immersed in their creative works. So paracraft is a very rich world, in which you can learn many things. If looking from a more traditional education perspective, paracraft is full of mathematical and computational ideas, full of architecture design, interior design, full of camera languages, directing, screenplay, story telling, video editing, video cutting and other creative skill. But in paracraft, we intentionally play down these traditional knowledge perspectives. We put more emphasis on playing, exploring, experiencing, self-reflecting on your significant experiences, building up models of knowledge in self-directed ways, applying your self knowledge in creating of your 3D works, expressing yourself, sharing with the world and communicating with other lives. This is our understanding of education, what education is essentially about. It is Life Education. When it comes to knowledge, we emphasize self knowledge. Whatever children are interested in, they can set themselves up for a journey of exploration and learning; As long as it has personal exploration and experiences, as well as reflection on those experiences to build up a better understanding of the whole, it is learning; As long as it is with your personal understanding of the whole built on top of your personal experiences and can be applied, it is knowledge. Parents don’t need to worry about children not learning or not learning the right thing if their children can “keep themselves busy” with something.</p>
      <p> How do you know what you are good at and what you like the best? What are your talents? What is special about you? You have to try things to find out. Paracraft is such a rich world that all kids can find what they enjoy doing within. Maybe you cannot discover your talents in sports and singing through paracraft, but for many other things paracraft can help you discover yourself. Being able discover oneself at an early age can be a great fortune for living one’s life and for one’s ultimate happiness. Too sad that too many people spent around 20 years in school, still not knowing what they like to do. Here in paracraft, we understand that discovering oneself is one essential part of education.</p>
      <p> If discovering oneself can be said of starting of one’s education, expressing oneself can be said to be the ultimate purpose of education. We sing, we dance, we write, we build creative works, we change our environment, we make an impact on other people’s lives, all these are self-expression of life. The sense of existence of life hinges on this. Paracraft provides a powerful tool for people to express themselves through creative 3D works. You can check our users’ works to see how our users expressed themselves through their 3D works made in paracraft. Some of them you might have known for a long while but you only get to see the inside of their hearts or the beauty of their minds through their creative works. Some works might bring you to tears reminding you what life is about. We human beings long for expressing ourselves. Life wants to express itself. Some express with singing, some express through creative writing, some through sports. These are all forms of self-expression. Paracraft provides a rich way for one to express oneself through creative 3D works.</p>
      <p>Changing things around you, improving the surrounding environment, making an impact on others’ lives, is also a form of self-expression. Actually although singing, playing sports, writing, and producing other kinds of creative works are all forms of self-expressing, underneath lies the other side of it: creating beautiful things to make our world better. It is self-expressing, it is also reaching out, sharing, building things together, losing yourself in the activity of creating beauty or in the activity of togetherness with others. We cherish our individual uniqueness, we develop our uniqueness as life develops itself, and lose ourselves in our activities of creating beauty, connecting ourselves to the larger life, or returning ourselves to the original peacefulness, which is always together with our existence in the form of life. This is the Life Education we are talking about.</p>
      <p>To express yourself or to change the world, you need to empower yourself with skills. In paracraft, it is our knowledge that in order to freely participate in this increasingly sophisticated society people need to command several essential skills. Otherwise, one feels powerless.</p>
      <p>One of such essential skills is to be able to design and create artwork. In paracraft, you need to be able to build 2D or 3D artwork. You can build 3D scenes or object models with blocks, or if you need more precise models, you can use CAD in paracraft. You can also create videos with paracraft movie editor.</p>
      <p>If you need to add complex logic to your characters, you can write code. Software programming, in our view, is another essential skill that people of our modern world needs to grasp.</p>
      <p>So 2D or 3D artwork, CAD and software programming are the essential skills that we want our users to obtain through using paracraft. While using these skills creating your works, other skills like story telling, directing, designing, planning, project collaboration and so on as we mentioned earlier are also the skills you can learn in the process. This is our understanding of fluency with digital technology.</p>
      <p>In addition, it is our understanding that the core of software programming is abstract modeling, which is also the core of knowledge building. This is the underlying reason why software is becoming more and more universal in our lives, entering all different domains. The essence of “digitization” to us is providing digital representation of our knowledge of various domains through abstract modeling. Thus we need to learn programming not only because software is already universal in our lives, but also more deeply through learning of software programming we get to learn how to learn, how to explore and build up our knowledge.</p>
      <p>With this understanding of software programming, we see the inherent connection between artistic works and programming. For example, design, story telling, aesthetics sense are all essential in software programming as well. Software programming is an art, is craftsmanship. Like any other craft, it needs the same skills. In fact, we understand software programming as the bridge between the human world and the physical world, or the bridge between human science and natural science. Software programming is about creating life.</p>
      <p>So the two seemly different skills: artwork making and software programming are well unified in paracraft, one often leading to the other. This is probably the most beautiful part of paracraft: children initially drawn to one side can gradually develop interests in the other by finding the common language between them.</p>
      <p>Lastly I want to tell you that when kids come together working on a project, it is like in any sports team. They work hard, sweat themselves, taking all the pains. They learn to talk to each other, cooperate with each other, help out each other, bring out the best of everyone.</p>
      <p>Hope paracraft helps your children start a journey of life!</p>
    </div>
  </div>
</template>
<script>
export default {
  name: 'ParentLetter'
}
</script>
<style lang="scss" scoped>
.parent-letter {
  &-title {
    text-align: center;
    font-size: 32px;
    font-weight: bold;
  }
  &-box {
    &-left {
      vertical-align: unset;
      margin-right: 16px;
    }
    &-right {
      vertical-align: unset;
      margin-left: 16px;
    }
  }
  a {
    text-decoration: underline;
  }
}
</style>
